import = ["/home/bilal/.config/alacritty/themes/tokyo-night.toml"]

[font]
size = 11.0

[font.bold]
family = "SpaceMono Nerd Font Mono"

[font.bold_italic]
family = "SpaceMono Nerd Font Mono"

[font.italic]
family = "SpaceMono  Nerd Font Mono"

[font.normal]
family = "SpaceMono Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "Paste"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"

[window]
decorations = "none"
dynamic_padding = true
opacity = 0.9

[window.padding]
x = 10
y = 10

[shell]
program = "/usr/bin/tmux"
args = ["-u"]
